"""Shared enums, mirrored on the frontend in src/types/enums.ts."""

from __future__ import annotations

import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class ProjectStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    UPLOADING = "UPLOADING"
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class ProjectFileType(str, enum.Enum):
    FINAL_MESH = "FINAL_MESH"
    INITIAL_MESH = "INITIAL_MESH"
    THERMAL_DATA = "THERMAL_DATA"
    THERMAL_IMAGE = "THERMAL_IMAGE"
    CAMERA_METADATA = "CAMERA_METADATA"
    RESULT = "RESULT"
    REPORT = "REPORT"


class UploadStatus(str, enum.Enum):
    PENDING = "PENDING"
    UPLOADED = "UPLOADED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class JobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ProcessingStageName(str, enum.Enum):
    INPUT_VALIDATION = "INPUT_VALIDATION"
    MESH_ALIGNMENT = "MESH_ALIGNMENT"
    CAMERA_POSE_ESTIMATION = "CAMERA_POSE_ESTIMATION"
    THERMAL_PROJECTION = "THERMAL_PROJECTION"
    OCCLUSION_ANALYSIS = "OCCLUSION_ANALYSIS"
    TEMPERATURE_MAPPING = "TEMPERATURE_MAPPING"
    UV_GENERATION = "UV_GENERATION"
    THERMAL_BLENDING = "THERMAL_BLENDING"
    WEB_EXPORT = "WEB_EXPORT"
    REPORT_GENERATION = "REPORT_GENERATION"


class StageStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CameraPoseSource(str, enum.Enum):
    PROVIDED = "PROVIDED"
    ESTIMATED = "ESTIMATED"
    REFINED = "REFINED"


class ReportType(str, enum.Enum):
    THERMAL_ANALYSIS = "THERMAL_ANALYSIS"
    PROCESSING = "PROCESSING"
    QUALITY = "QUALITY"


class AuditAction(str, enum.Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_DELETED = "PROJECT_DELETED"
    FILE_UPLOADED = "FILE_UPLOADED"
    PROCESSING_STARTED = "PROCESSING_STARTED"
    PROCESSING_COMPLETED = "PROCESSING_COMPLETED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    REPORT_GENERATED = "REPORT_GENERATED"
